spring.application.name=bank-management

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bankDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=nor
spring.datasource.password=9981!Secure

spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

logging.level.org.springframework.jdbc.core=DEBUG

spring.security.user.name=admin
spring.security.user.password=1234