jdbc.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver
jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=bank_db;encrypt=false;trustServerCertificate=true
jdbc.user=sa
jdbc.password=YourStrong@Passw0rd