-- ==========================================
-- 1. 刪除所有資料表 (包含結構與資料)
-- 刪除順序：先刪除最末端的子表，逐層往上，最後刪除無相依性的主表
-- ==========================================

-- [第四層：最末端交易與明細表]
DROP TABLE IF EXISTS [CREDIT_CARD_BILL];
DROP TABLE IF EXISTS [CREDIT_CARD_TRANSACTION];
DROP TABLE IF EXISTS [CARD_APPLICATION_ITEM];  -- (新增) 信用卡申請明細
DROP TABLE IF EXISTS [REPAYMENT_RECORD];
DROP TABLE IF EXISTS [STOCK_TRANSACTION_RECORD];
DROP TABLE IF EXISTS [CUSTOMER_STOCK_HOLDING];
DROP TABLE IF EXISTS [TRANS_LOG];
DROP TABLE IF EXISTS [ADMIN_LOG];

-- [第三層：依賴主檔的關聯表]
DROP TABLE IF EXISTS [CREDIT_CARD];
DROP TABLE IF EXISTS [CARD_APPLICATION];       -- (新增) 信用卡申請主表
DROP TABLE IF EXISTS [LOAN_APPLICATION];
DROP TABLE IF EXISTS [KYC_RECORD];

-- [第二層：核心帳戶表]
DROP TABLE IF EXISTS [ACCOUNT];

-- [第一層：最頂層獨立主檔表]
DROP TABLE IF EXISTS [CUSTOMER];
DROP TABLE IF EXISTS [ADMINISTRATOR];
DROP TABLE IF EXISTS [CARD_TYPE];
DROP TABLE IF EXISTS [MERCHANT];
DROP TABLE IF EXISTS [STOCK_MASTER];
DROP TABLE IF EXISTS [stock_info];

GO