-- ==========================================

-- 1. 刪除所有資料表 (包含結構與資料)

-- ==========================================

DROP TABLE IF EXISTS [CREDIT_CARD_BILL];

DROP TABLE IF EXISTS [CREDIT_CARD_TRANSACTION];

DROP TABLE IF EXISTS [REPAYMENT_RECORD];

DROP TABLE IF EXISTS [STOCK_TRANSACTION_RECORD];

DROP TABLE IF EXISTS [CUSTOMER_STOCK_HOLDING];

DROP TABLE IF EXISTS [ADMIN_LOG];

DROP TABLE IF EXISTS [KYC_RECORD];

DROP TABLE IF EXISTS [LOAN_APPLICATION];

DROP TABLE IF EXISTS [CREDIT_CARD];

DROP TABLE IF EXISTS [TRANS_LOG];

DROP TABLE IF EXISTS [ACCOUNT];

DROP TABLE IF EXISTS [CUSTOMER];

DROP TABLE IF EXISTS [ADMINISTRATOR];

DROP TABLE IF EXISTS [CARD_TYPE];

DROP TABLE IF EXISTS [MERCHANT];

DROP TABLE IF EXISTS [STOCK_MASTER];

GO